use std::sync::OnceLock;

use futures::prelude::*;
use tarpc::server::{self, Channel};
use tarpc::{client, context};

// This is the service definition. It looks a lot like a trait definition.
// It defines one RPC, hello, which takes one arg, name, and returns a String.
#[tarpc::service]
trait World {
    /// Returns a greeting for name.
    async fn hello(name: String) -> String;
}

// This is the type that implements the generated World trait. It is the business logic
// and is used to start the server.
#[derive(Clone)]
struct HelloServer;

impl World for HelloServer {
    async fn hello(self, _: context::Context, name: String) -> String {
        format!("Hello, {name}!")
    }
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let (client_transport, server_transport) = tarpc::transport::channel::unbounded();

    let server = server::BaseChannel::with_defaults(server_transport);
    tokio::spawn(
        server
            .execute(HelloServer.serve())
            // Handle all requests concurrently.
            .for_each(|response| async move {
                tokio::spawn(response);
            }),
    );

    // WorldClient is generated by the #[tarpc::service] attribute. It has a constructor `new`
    // that takes a config and any Transport as input.
    let mut client = WorldClient::new(client::Config::default(), client_transport).spawn();

    // The client has an RPC method for each RPC defined in the annotated trait. It takes the same
    // args as defined, with the addition of a Context, which is always the first arg. The Context
    // specifies a deadline and trace information which can be helpful in debugging requests.
    let hello = client.hello(context::current(), "Stim".to_string()).await?;

    println!("{hello}");

    Ok(())
}

static S: OnceLock<HelloServer> = OnceLock::new();
fn init_service() -> Result<(), HelloServer> {
    S.set(HelloServer)
}

struct WorldSDK {
    client: WorldClient<tarpc::client::Channel<WorldRequest, WorldResponse>>,
}

struct Context {
    pub rpc: context::Context,
    pub is_rpc: bool,
}

impl WorldSDK {
    fn new<T>(config: ::tarpc::client::Config, client_transport: T) -> Self
    where
        T: ::tarpc::Transport<::tarpc::ClientMessage<WorldRequest>, ::tarpc::Response<WorldResponse>> + Send + 'static,
    {
        Self {
            client: WorldClient::new(config, client_transport).spawn(),
        }
    }
    async fn hello(self, ctx: Context, name: String) -> ::core::result::Result<String, ::tarpc::client::RpcError> {
        if ctx.is_rpc {
            self.client.hello(ctx.rpc, name).await
        } else {
            Ok(S.get().cloned().unwrap().hello(ctx.rpc, name).await)
        }
    }
}
